name: Linux Arm64

on:
  workflow_call:
    outputs:
      artifact_ids:
        value: ${{ jobs.build.outputs.artifact_ids }}
        description: Comma-separated list of artifact IDs for the release artifacts
    inputs:
      profile:
        required: false
        default: "release"
        type: string
      build-args:
        default: ""
        required: false
        type: string
      wpt-args:
        default: ""
        required: false
        type: string
      wpt:
        required: false
        type: boolean
      unit-tests:
        required: false
        default: false
        type: boolean
      build-libservo:
        required: false
        default: false
        type: boolean
      force-github-hosted-runner:
          required: false
          type: boolean
          default: false
      bencher:
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      profile:
        required: false
        default: "release"
        type: choice
        options: ["release", "debug", "production"]
      wpt-args:
        default: ""
        required: false
        type: string
      wpt:
        required: false
        type: boolean
      unit-tests:
        required: false
        default: false
        type: boolean
      build-libservo:
        required: false
        default: false
        type: boolean
      force-github-hosted-runner:
          required: false
          type: boolean
          default: false
      bencher:
        required: false
        default: false
        type: boolean

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash
  # Increment this to purge the cache (https://github.com/mozilla/sccache/blob/main/docs/GHA.md)
  SCCACHE_GHA_VERSION: 1
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CCACHE: "sccache"
  CARGO_INCREMENTAL: 0

jobs:
  build:
    name: Linux Arm64 Build
    runs-on: ubuntu-24.04-arm
    outputs:
      artifact_ids: ${{ steps.artifact_ids.outputs.artifact_ids }}
    steps:
      - uses: actions/checkout@v5
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: 1
          submodules: recursive
      # This is necessary to checkout the pull request if this run was triggered via a
      # `pull_request_target` event.
      - uses: actions/checkout@v5
        if: github.event_name == 'pull_request_target'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1
          submodules: recursive
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
          swap-storage: false
      - name: Set LIBCLANG_PATH env # needed for bindgen in mozangle
        run: echo "LIBCLANG_PATH=/usr/lib/llvm-18/lib" >> $GITHUB_ENV
      - name: Setup Python
        uses: ./.github/actions/setup-python
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Bootstrap dependencies
        timeout-minutes: 30
        run: |
          sudo apt update
          echo "wireshark-common wireshark-common/install-setuid boolean true" | sudo debconf-set-selections
          sudo apt install -qy tshark
          ./mach bootstrap --yes --skip-lints

      # Always install crown, even on self-hosted runners, because it is tightly
      # coupled to the rustc version, and we may have the wrong version if the
      # commit we are building uses a different rustc version.
      - name: Install crown
        run: cargo install --path support/crown

      - name: Build (${{ inputs.profile }})
        run: |
          ./mach build --use-crown --locked --profile ${{ inputs.profile }} ${{ inputs.build-args }}
          mv target/cargo-timings target/cargo-timings-linux-arm64
      - name: Smoketest
        run: xvfb-run ./mach smoketest --profile ${{ inputs.profile  }}
      - name: Script tests
        run: ./mach test-scripts
      - name: Unit tests
        id: run_unit_tests
        if: ${{ inputs.unit-tests }}
        env:
          NEXTEST_RETRIES: 2 # https://github.com/servo/servo/issues/30683
          LANG: en-US
        run: ./mach test-unit --profile ${{ inputs.profile }} --nextest-profile ci
      # We upload the test-results to Codecov to help us identify flaky unit-tests.
      - name: Upload test results to Codecov
        # Upload test results to Codecov, also for failed unit-tests, but only
        # if unit-tests were supposed to run, and not if they were skipped (e.g., due
        # to an earlier failure).
        if: ${{ !cancelled() && steps.run_unit_tests.conclusion != 'skipped' }}
        uses: codecov/codecov-action@v5
        with:
          report_type: test_results
          files: target/nextest/ci/junit.xml
          disable_search: true
          flags: unittests,unittests-linux-arm64,unittests-linux-arm64-${{ inputs.profile }}
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Devtools tests
        if: ${{ false && inputs.unit-tests }} # FIXME #39273
        run: ./mach test-devtools --profile ${{ inputs.profile }}
      - name: Archive build timing
        uses: actions/upload-artifact@v7
        with:
          name: cargo-timings-linux-arm64-${{ inputs.profile }}
          # Using a wildcard here ensures that the archive includes the path.
          path: target/cargo-timings-*
          if-no-files-found: error
      - name: Build mach package
        run: ./mach package --profile ${{ inputs.profile }}
      - name: Upload artifact for mach package
        uses: actions/upload-artifact@v7
        id: upload-tarball
        with:
          name: ${{ inputs.profile }}-binary-linux-arm64
          path: target/${{ inputs.profile }}/servo-tech-demo.tar.gz
          if-no-files-found: error
      - name: Collect artifact IDs needed by the release workflow
        id: artifact_ids
        shell: bash
        run: |
          echo "artifact_ids=${{steps.upload-tarball.outputs.artifact-id}}" >> $GITHUB_OUTPUT

  bencher:
    needs: ["build"]
    if: ${{ inputs.bencher && inputs.profile != 'debug' && github.event_name != 'workflow_dispatch' && github.event_name != 'merge_group' }}
    uses: ./.github/workflows/bencher.yml
    with:
      target: "linux-arm64"
      profile: ${{ inputs.profile }}
      compressed-file-path: ${{ inputs.profile }}-binary-linux-arm64/servo-tech-demo.tar.gz
      binary-path: servo/servoshell
      file-size: true
      speedometer: false
      dromaeo: false
    secrets: inherit

  build-libservo:
    if: ${{ inputs.build-libservo }}
    name: Build libservo and MSRV check
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: 1
          submodules: recursive
      # This is necessary to checkout the pull request if this run was triggered via a
      # `pull_request_target` event.
      - uses: actions/checkout@v5
        if: github.event_name == 'pull_request_target'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1
          submodules: recursive
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
          swap-storage: false
      - name: Set LIBCLANG_PATH env # needed for bindgen in mozangle
        run: echo "LIBCLANG_PATH=/usr/lib/llvm-18/lib" >> $GITHUB_ENV
      - name: Setup Python
        uses: ./.github/actions/setup-python
      - name: Determine MSRV
        id: msrv
        uses: ./.github/actions/parse_msrv
      - name: Install MSRV
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.msrv.outputs.rust_version }}
      # We can remove this after upgrading to Rust 1.90, but for now
      # installing lld is the easiest way to get it in path.
      - name: install lld
        run: sudo apt-get install -y lld
      - name: Compile libservo with MSRV
        env:
          # lld seems to use less memory and prevents OOM errors during linking.
          # We can remove this after upgrading to Rust 1.90, where lld will be the default.
          RUSTFLAGS: "-C link-arg=-fuse-ld=lld"
        run: |
          cargo +${{ steps.msrv.outputs.rust_version }} build -p servo --locked
